### ISSUE TITLE
Update to Node > 12

### ISSUE THREAD

**Issue by paulschreiber** [agenthunt/conventional-commit-checker-action#4]
From GitHub:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

`agenthunt/conventional-commit-checker-action@v1.0.0` was flagged as needing updating.

**Comment by AmmarArnt** [comment]
Would be awesome to get this merged!
